### ISSUE TITLE
 While building for Mac Catalyst, no library for this platform was found in 'WebRTC.xcframework'.

### ISSUE THREAD

**Issue by nikhil191090** [alexpiezo/WebRTC#4] opened 2020-10-09 13:30 UTC
Getting this issue while try to run on mac

**Comment by nikhil191090** [comment] 2020-10-09 14:30
@alexpiezo Please Help i am kind of stuck here

**Comment by alexpiezo** [comment] 2020-10-15 14:15
@nikhil191090 Unfortunately this build doesn't support Mac Catalyst. At least until official WebRTC supports the arch

**Comment by alexpiezo** [comment] 2020-10-15 15:24
Duplicate of #1

**Closed by alexpiezo** 2020-10-15 15:24 UTC
